version: '3'
services:
    web:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - /opt/app/node_modules
          - .:/opt/app
        ports:
          - '3000:3000'
        tty: true