apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: myapp-backend
    type: backend
spec:
  template:
    metadata:
      name: backend-pod
      labels:
        app: myapp-backend
        type: backend

    spec:
      containers:
        - name: backend
          image: backend

          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: '6379'
  replicas: 3
  selector:
    matchLabels:
      type: backend