apiVersion: v1
kind: Service

metadata:
  name: myapp-service

spec:
  type: NodePort
  ports:
    - targetPort: 4000
      port: 4000
      nodePort: 30008

  selector:
    app: myapp-backend
    type: backend